<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IQA-Kapil" name="com.scripts.regTestCases.CandidateDashboard" tests="1" failures="0" timestamp="26 Apr 2018 12:21:17 GMT" time="102.169" errors="1">
  <testcase name="verifyPersonalPlanningRedirections" time="102.169" classname="com.scripts.regTestCases.CandidateDashboard">
    <error type="org.testng.SkipException" message="">
      <![CDATA[org.testng.SkipException: 
	at com.scripts.lib.commonFunction.CommonUtills.click(CommonUtills.java:482)
	at com.scripts.businessLogic.CandidateDashboardBL.verifyApplyNowIconRedirection(CandidateDashboardBL.java:132)
	at com.scripts.businessLogic.CandidateDashboardBL.verifyJobsOfInterestSection(CandidateDashboardBL.java:122)
	at com.scripts.regTestCases.CandidateDashboard.verifyPersonalPlanningRedirections(CandidateDashboard.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- verifyPersonalPlanningRedirections -->
</testsuite> <!-- com.scripts.regTestCases.CandidateDashboard -->
